p8105\_hw6\_yg2625
================
Yue Gu
November 25, 2018

Library
=======

``` r
library(tidyverse)
```

Problem 1
=========

Import data
-----------

``` r
homi_raw = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
head(homi_raw, 10)
```

    ## # A tibble: 10 x 12
    ##    uid   reported_date victim_last victim_first victim_race victim_age
    ##    <chr>         <int> <chr>       <chr>        <chr>       <chr>     
    ##  1 Alb-~      20100504 GARCIA      JUAN         Hispanic    78        
    ##  2 Alb-~      20100216 MONTOYA     CAMERON      Hispanic    17        
    ##  3 Alb-~      20100601 SATTERFIELD VIVIANA      White       15        
    ##  4 Alb-~      20100101 MENDIOLA    CARLOS       Hispanic    32        
    ##  5 Alb-~      20100102 MULA        VIVIAN       White       72        
    ##  6 Alb-~      20100126 BOOK        GERALDINE    White       91        
    ##  7 Alb-~      20100127 MALDONADO   DAVID        Hispanic    52        
    ##  8 Alb-~      20100127 MALDONADO   CONNIE       Hispanic    52        
    ##  9 Alb-~      20100130 MARTIN-LEY~ GUSTAVO      White       56        
    ## 10 Alb-~      20100210 HERRERA     ISRAEL       Hispanic    43        
    ## # ... with 6 more variables: victim_sex <chr>, city <chr>, state <chr>,
    ## #   lat <dbl>, lon <dbl>, disposition <chr>

Data manipulation
-----------------

-   Create a city\_state variable, and a binary variable
-   Omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO; Tulsa, AL
-   Modifiy victim\_race to have categories white and non-white
-   Transform victim\_age as numeric

``` r
homi_create = 
  homi_raw %>% 
  mutate(city_state = paste(city, state, sep = ", "),
         solved = ifelse(disposition == "Closed without arrest" | disposition == "Open/No arrest", 0, 1)) %>% 
  filter(city_state != "Dallas, TX" , city_state != "Phoenix, AZ", city_state != "Kansas City, MO", city_state != "Tulsa, AL") %>% 
  mutate(victim_race = ifelse(victim_race == "White", "white", "nonwhite"),
         victim_race = fct_relevel(victim_race, "white"),
         victim_age = as.numeric(victim_age))
```

    ## Warning in evalq(as.numeric(victim_age), <environment>): NAs introduced by
    ## coercion

``` r
class(homi_create$victim_age)
```

    ## [1] "numeric"

``` r
class(homi_create$victim_race)
```

    ## [1] "factor"

As required, binary variable *solved* have value 0 if the case is unsolved, have value 1 if the case is solved, *victim\_race* have categories white and non-white as factors and *victim\_age* are numeric.

Fit regression
--------------

-   For the city of Baltimore, MD, use the glm function to fit a logistic regression with resolved vs unresolved as the outcome and victim age, sex and race as predictors
-   Save the output of glm as an R object

``` r
balt_fit_log = 
  homi_create %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(solved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())
```

-   Apply the broom::tidy to this object
-   Obtain the estimate and confidence interval of the adjusted odds ratio for solving homicides comparing non-white victims to white victims keeping all other variables fixed

``` r
balt_fit_log %>% 
  broom::tidy() %>%
  mutate(OR = exp(estimate),
         OR_low = exp(estimate - qnorm(1-0.05/2)*std.error),
         OR_high = exp(estimate + qnorm(1-0.05/2)*std.error)) %>%
  select(term, estimate, OR, OR_low, OR_high) %>% 
  knitr::kable(digits = 3)
```

| term                 |  estimate|     OR|  OR\_low|  OR\_high|
|:---------------------|---------:|------:|--------:|---------:|
| (Intercept)          |     1.186|  3.274|    2.067|     5.186|
| victim\_age          |    -0.007|  0.993|    0.987|     0.999|
| victim\_sexMale      |    -0.888|  0.412|    0.315|     0.537|
| victim\_racenonwhite |    -0.820|  0.441|    0.313|     0.620|

With the output, we could know the adjusted odds ratio for solving homicides comparing non-white victims to white victims is 0.441 keep all else fixed. And we are 95% confident that the adjusted odds ratio will fall in the range from 0.313 to 0.620.

-   Run glm for each of the cities in your dataset, and extract the adjusted odds ratio (and CI) for solving homicides comparing non-white victims to white victims
